version: "3"
services:
  mariadb:
    build:
      context: mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes: 
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./db_data